[project]
name = "meliris"
version = "0.1.0"
description = "An Intelligent System for LRC Enhancement based on Vocal Detection"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mutagen>=1.46.0",
    "librosa>=0.10.1",
    "numpy>=1.23",
    "torch>=2.0",
    "tqdm>=4.64",
]
